-- ===========================================================================
-- DDL - Esquema del modulo de ventas (H2)
-- ===========================================================================
-- Spring Boot ejecuta este schema.sql automaticamente al arrancar cuando
-- spring.sql.init.mode=always. Para que NO choque con Hibernate, dejamos
-- spring.jpa.hibernate.ddl-auto=none (ver application.yml): aqui mandamos
-- nosotros el esquema, no Hibernate.
--
-- El orden de creacion respeta las claves foraneas: primero las tablas
-- "padre" (clientes, producto, pagos) y luego las que dependen de ellas.
-- ===========================================================================

-- Idempotencia: al reiniciar la app en memoria arrancamos de cero.
DROP TABLE IF EXISTS detalle_pedido;
DROP TABLE IF EXISTS pedidos;
DROP TABLE IF EXISTS pagos;
DROP TABLE IF EXISTS clientes;
DROP TABLE IF EXISTS producto;

-- --- Catalogo de productos (entidad Producto, ya existente) -----------------
CREATE TABLE producto (
    id        INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(255),
    precio    DOUBLE         NOT NULL,
    categoria VARCHAR(255)
);

-- --- Clientes (lado "uno" de 1..N con pedidos) ------------------------------
CREATE TABLE clientes (
    id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    email  VARCHAR(150) NOT NULL UNIQUE            -- email unico (regla de negocio 409)
);

-- --- Pagos (lado inverso del 1..1 con pedido) -------------------------------
-- 'metodo' guarda el nombre del enum MetodoPago (EnumType.STRING).
CREATE TABLE pagos (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metodo     VARCHAR(20)   NOT NULL
               CHECK (metodo IN ('EFECTIVO','TARJETA','TRANSFERENCIA','YAPE_PLIN')),
    monto      NUMERIC(12,2) NOT NULL,             -- dinero: NUMERIC, nunca float
    fecha_pago TIMESTAMP     NOT NULL
);

-- --- Pedidos (dueno de la FK hacia cliente y hacia pago) --------------------
-- 'estado' guarda el nombre del enum EstadoPedido (EnumType.STRING).
-- pago_id es UNIQUE porque la relacion Pedido<->Pago es 1..1.
CREATE TABLE pedidos (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha      TIMESTAMP   NOT NULL,
    estado     VARCHAR(20) NOT NULL
               CHECK (estado IN ('PENDIENTE','PAGADO','ENVIADO','ENTREGADO','CANCELADO')),
    cliente_id BIGINT      NOT NULL,
    pago_id    BIGINT      UNIQUE,
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id),
    CONSTRAINT fk_pedido_pago    FOREIGN KEY (pago_id)    REFERENCES pagos (id)
);

-- --- Detalle de pedido (tabla de union con CLAVE COMPUESTA) -----------------
-- PK = (pedido_id, producto_id): un producto no se repite como linea en el
-- mismo pedido. Es el reflejo del @EmbeddedId + @MapsId de la entidad.
CREATE TABLE detalle_pedido (
    pedido_id       BIGINT        NOT NULL,
    producto_id     INTEGER       NOT NULL,
    cantidad        INTEGER       NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,        -- precio historico al vender
    PRIMARY KEY (pedido_id, producto_id),
    CONSTRAINT fk_detalle_pedido   FOREIGN KEY (pedido_id)   REFERENCES pedidos (id),
    CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id) REFERENCES producto (id)
);
